# Generated by Django 2.2 on 2019-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
